Widgets/Sidebar/Panel/PanelPopup.qml
Just set Network Card's height to 80 to match Power Profile's
=> Fix: Corrected Network Card Height

Bar/Modules/AudioDeviceSelector.qml, Bar/Modules/Battery.qml, Services/Sysinfo.qml, Services/WallpaperManager.qml, Widgets/Sidebar/Panel/System.qml
For battery percentage being as 0 to 1 float (needed to x100)
and shellRoot vs shellDir deperication edits
fix audio device selector signal name: Duplicate signal name: invalid override of property change signal or superclass signal ?
=> Quick fixs

Bar/Bar.qml, Bar/Modules/ActiveWindow.qml, Bar/Modules/Brightness.qml, Bar/Modules/CustomTrayMenu.qml, Bar/Modules/Workspace.qml, Components/Cava.qml, Components/StyledTooltip.qml, Helpers/Weather.js, Services/Niri.qml, Services/WorkspaceManager.qml, Settings/Settings.qml, Settings/Theme.json, Settings/Theme.qml, Widgets/Notification/NotificationPopup.qml, Widgets/Sidebar/Config/ProfileSettings.qml, shell.qml
As discussed on discord, here is my take on minor issues I encountered.
Keep up the great work!
=> Minor QOL improvements

Bar/Modules/Battery.qml, Bar/Modules/Brightness.qml, Bar/Modules/Volume.qml, Components/PillIndicator.qml
- Convert the icon to a PillIndicator
- Better looking horizontal battery icons
- PillIndicator now supports conditionnal autoHide
=> Battery widget rework

Bar/Bar.qml, Bar/Modules/Brightness.qml
+ Tray moved to the very left.
=> Brightness indicator is not shown if brightness < 0

Services/WallpaperManager.qml
- avoid a bunch of warning in QS
- avoid empty/non working thumbnails on the wallpaper manager
=> Removed all the non-working image formats

Widgets/LockScreen/BatteryCharge.qml, Widgets/LockScreen/LockScreen.qml, Widgets/Sidebar/Panel/System.qml, shell.qml
- relocated lockscreen to its own directory
=> LockScreen: Added a battery indicator

Bar/Bar.qml, Bar/Modules/Media.qml, Bar/Modules/SystemTray.qml, Bar/Modules/Workspace.qml, Widgets/LockScreen/LockScreen.qml, Widgets/Overview.qml, Widgets/Sidebar/Config/ProfileSettings.qml, Widgets/Sidebar/Panel/Music.qml, Widgets/Sidebar/Panel/QuickAccess.qml, Widgets/Sidebar/Panel/System.qml
=> Revert "Remove qt5-compat"

.gitignore, Widgets/Sidebar/Panel/WifiPanel.qml
detect existing early when shell startup, add refresh button on wifi panel, i also change button from connect into a icon
=> fix: exisiting support network

Components/Avatar.qml, Services/WallpaperManager.qml, Widgets/LockScreen/LockScreen.qml, Widgets/Sidebar/Config/ProfileSettings.qml, Widgets/Sidebar/Config/WallpaperSettings.qml, Widgets/Sidebar/Panel/PanelPopup.qml, Widgets/Sidebar/Panel/WallpaperPanel.qml
- Swww: allow all images formats supported by Swww but only show the one we can render in the panel
- Fix: timer should be restarted when selecting a wallpaper
- Fix: avoid recomputing selected thumbnail by altering the border width
- Removed LazyLoader as it was not helping
=> Wallpaper refining

Bar/Modules/Applauncher.qml, Bar/Modules/Battery.qml, Bar/Modules/Volume.qml, Components/Avatar.qml, Components/StyledTooltip.qml, Helpers/Time.js, Widgets/LockScreen/LockScreen.qml, Widgets/Sidebar/Config/SettingsModal.qml, Widgets/Sidebar/Panel/BluetoothPanel.qml, Widgets/Sidebar/Panel/WallpaperPanel.qml, Widgets/Sidebar/Panel/WifiPanel.qml
See details in commit messages below.
This should fix #66 and #75
=> UI improvements

Bar/Modules/Media.qml
Removing layer stuff and replacing with ClippingRectangle
=> Fixed album image not appearing on bar 

Commons/Settings.qml, Modules/Background/Background.qml, Modules/Background/Overview.qml, Modules/SettingsPanel/Tabs/WallpaperTab.qml, Shaders/frag/wp_stripes.frag
- Added a toggle for Noctalia-shell wallpaper management
- fix shader error
=> Added a toggle for Noctalia-shell wallpaper management

Modules/Bar/Widgets/KeepAwake.qml, Services/BarWidgetRegistry.qml
https://github.com/user-attachments/assets/ff4c52ee-c5cd-48b6-82e4-de3180e0eedc
=> feat: keep awake bar widget

Assets/ColorScheme/Catppuccin.json
Also changed Green to Teal in Mocha and a few minor tweaks for readability while sticking to official colors [here](https://catppuccin.com/palette/).
=> Updated Catppuccin to use more of the official colors.

Assets/ColorScheme/Everforest.json, flake.nix
An everforest colorsheme.
I referenced the vim everforest. [Palette is here](https://github.com/sainnhe/everforest/blob/master/palette.md#palette-variants)
=> Everforest

Assets/ColorScheme/Kanagawa.json
This adds the Kanagawa colorscheme (only available in dark).
=> Kanagawa colorscheme

Modules/Bar/Widgets/Workspace.qml
The size was not uniform between horizontal and vertical width/hight for current workspace.
=> chore: adjust to maintain visual proportion

Modules/OSD/OSD.qml
=> Initialize volume silently

Widgets/NRadioButton.qml, Widgets/NSlider.qml, Widgets/NToggle.qml
Sometimes the circles of Toggles and the slider were off centered ever so slightly. I believe I've resolved this with a bit of rounding, and occasionally ditching ImplicitHeight for Height. I don't ***THINK*** that I broke anything.
before:
after:
=> Centered circles

flake.nix
This uses the new `settings-default.json` to set default values in the flake.
It means that users configuring with the flake using attribute sets can now set a partial configuration.
=> feat(flake): deep merge settings with defaults

Assets/Matugen/Matugen.qml
=> chore: refresh ghostty configuration

Services/BrightnessService.qml
Fix brightness sync after external command changes, improve brightness module compatibility
=> Fix brightness sync after external command changes

.zed/settings.json
Adds the exact command used for formatting QML files for Zed :)
=> chore(devex): create Zed settings file for qmlfmt

Services/IdleInhibitorService.qml
As discussed in https://github.com/noctalia-dev/noctalia-shell/issues/407
=> systemd-inhibit: remove handle-lid-switch

Modules/Settings/Tabs/DisplayTab.qml
=> fix(settings): Correct brightness slider layout issues
