noctalia-dev/noctalia-shell

Widgets/Background.qml
Widgets/LockScreen.qml
Widgets/Overview.qml

I'm not using SWWW as I don't really change my wallpaper that often.
This PR addresses a couple issues with the basic wallpaper/overview implementation when not using SWWW daemon.
- Fix: The wallpaper was only applied to the primary screen.
- Improve the look of the blurred backdrop by applying a slight tint over the image (based on theme) which makes things look better imo.
- Also tinted the lockscreen in the same way.

Wallpaper improvements

---

Bar/Modules/SystemInfo.qml
Bar/Modules/Taskbar.qml
Components/StyledTooltip.qml
README.md

- Readme: removed requirement for qt6-5compat as it is no longer necessary.
- Taskbar vs SystemInfo: Found a weird bug where the width of the SystemInfo component would be a float, and that would affect rendering of the following widget,  the taskbar icons would be all blurry. Fixing the width of the SystemInfo to avoid this.
- Taskbar: It re-uses the same tooltip across all icons and the tooltip dimensions where not properly updated when the text changed.  Also added a basic truncate with ellipsis to avoid super large tooltip (ex: when hovering a browser icon.)

Taskbar fixes + misc

---

Widgets/SidePanel/System.qml

command: ["sh", "-c", "uptime | awk -F 'up ' '{print $2}' | awk -F ',' '{print $1}' | xargs"]
This old command doesn't work if the system's uptime output is in another language. It just outputs nothing, which results in uptime not being displayed.

Update uptime command

---

Services/WorkspaceManager.qml

special workspaces (negative in hyprland) work as a toggle not a click to nav. so they were giving an error when clicking a repeater item with one of them resulted in an error and nothing happening, 
`WARN quickshell.hyprland.ipc: Dispatch request "workspace -96" failed with error "Previous workspace doesn't exist"`
in my project I set it up with 2 widgets, one for normals one for specials, let me know your thoughts

stop showing negative workspaces (till proper way of dealing with them

---

Commons/Settings.qml
Commons/WidgetLoader.qml
Modules/Bar/Widgets/ArchUpdater.qml
Modules/SettingsPanel/Tabs/BarTab.qml
Services/ArchUpdaterService.qml

- Adds an **Arch Linux updater button** to the system bar  
- **Requires**: `pacman-contrib` package  
- **Uses**: `xdg-terminal-exec` (currently hardcoded; can be customized manually by editing)  
- A **Title** is set for the update window (can be used to float it and such)  
- Checks/polls updates via `checkupdates` at intervals  
- Handles notifications and errors  
- Initiates system update  
- Widget displays:
- Update status  
- Tooltips with package details 
- Trigger update when availble or `checkupdates` manually  
- New `showArchUpdater` Toggle available in the **bar settings panel** to enable/disable feature

Archlinux updater widget

---

Commons/Settings.qml
Modules/Bar/Widgets/Workspace.qml
Modules/SettingsPanel/Tabs/BarTab.qml

New option in settings for adding the workspace names onto the workspace indicator on the bar.
I use Hyprland but I installed Niri to see how workspaces are handled there and as far as I can tell, they don't have names, correct me if I am wrong though.

Added setting for workspace names

---

flake.nix

There seems to be a small discrepancy between the NixOS install guide and what the flake.nix actually provides. Nothing major, but there are two solutions:
1. Change the "quickshell.packages.${system}.default" on step 2 to "inputs.noctalia.defaultPackage.${pkgs.system}"
2. Add a proper 'default' to the Flake.nix
Both options work just as well, but I think the latter is the 'proper' convention. I've gone ahead with doing the second solution on this pull request instead of changing the install guide.
I was also getting errors with how the 'formatter' was setup, so I sorted that too. 
**Side note:** I'm not sure if you have a preferred formatting for the code, so sorry ahead of time on that.

small flake.nix fix - providing a proper 'default' and fixing formatter errors

---

Assets/Matugen/matugen.toml
Assets/Matugen/templates/kitty.conf

Based off the previous version but I changed some that I found had too low contrast compared to the background. I also changed it so existing terminals will reload the color theme using the post_hook.
I've attached some screenshots with different color wallpapers. Let me know what you think.

Added kitty matugen template

---

Services/BrightnessService.qml

Problem
- Issue: “ddcutil freezes the notebook monitor if is not supports ddc/ci”.
- Root cause: We could end up issuing DDC VCP commands for displays that don’t actually support DDC/CI, which can hang some eDP laptop panels.
Solution
- Only ever run ddcutil get/set VCP on monitors positively identified as DDC/CI-capable.
- Use full ddcutil detect output to determine support and bus, then filter out non‑DDC panels.
What changed
- DDC detection:
- Switched to ddcutil detect --sleep-multiplier=0.5.
- Parse “Model:” and “I2C bus: /dev/i2c-N”.
- Detect “This monitor does not support DDC/CI” and set isDdc accordingly.
- root.ddcMonitors now contains only isDdc === true entries (shape: { model, busNum, isDdc }).
- Added per‑display Logger.log line to verify detection.
- Monitor logic:
- …

Prevent notebook panel freezes when DDC/CI is not supported

---

Modules/Bar/Widgets/Battery.qml

Assuming test mode is used to test out the battery widget when the machine has not battery; however, it was left enabled :D (I was confused why my laptop battery was low when it has been changing xD)

disable test mode for battery widget.

---

Modules/Bar/Widgets/KeyboardLayout.qml

fix: align KeyboardLayout widget with other bar components

---

Modules/Launcher/Plugins/ClipboardPlugin.qml

To replicate with items no clipboard i go to ">clip clear" 
and next go to ">clip" 
doing that show message "Loading clipboard history..."
with no items on the clipboard.

fix: message when no items on clipboard

---

Modules/Launcher/Plugins/ApplicationsPlugin.qml

With these changes launching steam games works fine now. Everything else launches as well. 
Terminal applications like fish or btop don't launch, so if an application is specified as runInTerminal I just use the previous command.

Fix steam games not launching with app2unit

---

Modules/LockScreen/LockContext.qml
Modules/LockScreen/LockScreen.qml

Better fingerprint integration by removing the check for empty password.
With this change, fingerprint works the same way as everywhere else for me on NixOS:
In NixOS configuration:
```
services.fprintd.enable = true;
```
And in the lock screen:
1. Press Enter
2. "Authenticating..." is shown
3. In this moment scan your finger on fingerprint scanner
4. Screen unlocks
Note:
Without this change, it will ask for the password first, and since the password for `login` in PAM is always enabled on NixOS, you need to put something in, and obviously it has to be a correct password.

Fix for fingerprint flow on lock screen

---

flake.nix

Additions to the `flake.nix`:
- `nixosModule`: a systemd service which you activate with `services.noctalia-shell.enable = true`
- `homeModule`: an option to configure settings an attribute set, string or filepath
- `homeModule`: an option to configure colors an attribute set, string or filepath
- Formats the flake using `nixfmt-rfc-style`
For Nix users, Noctalia provides both NixOS and home-manager modules:
This will automatically start after Niri. 
>[!NOTE]
> For **Hyprland**, it depends on how you configure your systemd service. Many options like UWSM will setup `graphical-session.target` for you an _should_ work by default. This has not been tested, let us know if you find bugs.
```nix
{
imports = [ inputs.noctalia-shell.nixosModules.default ];
services.noctalia-shell = {
enable = …
```

nix flake: systemd service + home manager settings

---

Modules/Bar/Widgets/SidePanelToggle.qml
Modules/SettingsPanel/Bar/WidgetSettings/SidePanelToggleSettings.qml
Services/BarWidgetRegistry.qml

Adds a feature allowing users to select a custom image file to be used as the icon for the SidePanelToggle widget.
- Introduces a "Browse File" button in the widget's settings dialog, utilizing the `NFilePicker` component.
- An `NImageCircled` preview of the selected custom icon is now shown in the settings.
- The display logic for the widget is updated to prioritize the custom icon path over the library icon and distro logo.

feat(bar): Allow custom icon for SidePanelToggle

---

Assets/settings-default.json
Commons/Settings.qml
Modules/Bar/Widgets/Microphone.qml
Modules/Bar/Widgets/Volume.qml
Modules/OSD/OSD.qml
Modules/Settings/Tabs/AudioTab.qml
Services/AudioService.qml

What is done:
- Allow volume overdrive (going above 100%; configurable, default false)
- Fix inconsistent volume values
- Fix shown volume after sink/source switch

Audio changes

---

.zed/settings.json

fixes strange behavior, I should've RTFM'd about `buffer_path`

fix: zed formatting command

---

flake.nix

This addresses a problem where the launcher is not able to actually launch any applications when it is started by a systemd unit generated by Nix.
The search path would typically be inherited by a systemd unit, but Nix's unit generator will assign a specific, minimal PATH that only includes the unit's runtime dependencies.
I ended up unsetting the autogenerated `PATH`, but it's possible that this may violate some expectation of `noctalia-shell`; the set of things on my path as a user is not guaranteed to overlap with the set of things required by derivation that generates the systemd unit.
Another option I considered was setting the `PATH` to effectively the same thing that it is set to when I read it from a terminal on my system. This is more or less the approach that `hyperland` uses to …

fix: Unset `PATH` that is auto-generated by Nix

---

Modules/ControlCenter/Cards/WeatherCard.qml

Fixes regression caused by 4ed16d795e73fafb4412cab8c27abcf870d76265 where the weather overflowing when using wider fonts
| Before | After |
|--------|--------|
| <img width="816" height="1211" alt="image" src="https://github.com/user-attachments/assets/38608e41-d07e-4204-99de-27f9e3270879" /> | <img width="728" height="1186" alt="image" src="https://github.com/user-attachments/assets/bd4f1156-d932-4477-9d78-7810a6007ec5" /> |

fix: clip overflowed weather entries

---

Modules/Bar/Widgets/NotificationHistory.qml
Modules/Notification/NotificationHistoryPanel.qml
Services/IPCService.qml

Currently only clicking on the notification icon will update timestamp and mark all notifications as read, with this change it will be possible when opening with `qs -c noctalia-shell ipc call notifications toggleHistory`. This enables marking notifications as read programmatically via IPC.

update lastSeenTs in notifications toggleHistory ipc call

---

.github/workflows/update-aur-package.yml

- Update the `GIT_SSH_COMMAND` to include more options
- Future outages fail faster and leaver clearer logs

chore(ci): update AUR package workflow

---

Modules/Settings/Tabs/ColorSchemeTab.qml

The color scheme grid previously used a fixed number of columns, which caused cards to be partially clipped when the window width was narrow.
This change makes the number of columns dynamically calculated based on the available width. It ensures the grid layout gracefully adapts from 3 (or more) columns down to 1 column, preventing content overflow and clipping.
This fixes a UI bug where the right-side content of color scheme cards was not visible at certain window widths.

fix(settings): make color scheme grid layout responsive

---

Modules/Bar/Widgets/Taskbar.qml
Modules/Bar/Widgets/Workspace.qml
Services/CompositorService.qml
Services/HyprlandService.qml
Services/NiriService.qml
Services/SwayService.qml

Brings basic sway support
focus/close window is kinda buggy with the current setup. I found the Toplevel object[1] has an convenient `activate()` method that might work but I'm not sure it's a good idea to pass around this object instead of the hash of details like now.
Fixes #403 
1: https://quickshell.org/docs/v0.1.0/types/Quickshell.Wayland/Toplevel/

Basic sway support
